In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("layoffs.csv")

In [5]:
df.dtypes

company                 object
location                object
total_laid_off         float64
date                    object
percentage_laid_off    float64
industry                object
source                  object
stage                   object
funds_raised           float64
country                 object
date_added              object
dtype: object

In [6]:
df.head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Trustly,"Stockholm, Non-U.S.",200.0,9/17/2026,NaN,Finance,https://tech.eu/2026/09/17/swedish-fintech-tru...,Acquired,28.0,Sweden,9/17/2026
1,Bluevine,"Bengaluru, Non-U.S.",80.0,9/17/2026,NaN,Finance,https://www.ndtv.com/offbeat/team-of-80-indian...,Unknown,769.0,India,9/17/2026
2,Pulley,SF Bay Area,NaN,9/15/2026,1.0,Finance,https://www.businessinsider.com/pulley-shuts-d...,Series B,50.0,United States,9/16/2026
3,Oracle,SF Bay Area,NaN,9/14/2026,NaN,Other,https://www.businessinsider.com/oracle-begins-...,Post-IPO,NaN,United States,9/16/2026
4,Bitcoin Suisse,"Zurich, Non-U.S.",60.0,9/11/2026,0.5,Crypto,https://www.reuters.com/business/world-at-work...,Series A,NaN,Switzerland,9/14/2026

In [7]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [8]:
df[["date", "date_added"]].dtypes

date          datetime64[ns]
date_added    datetime64[ns]
dtype: object

In [9]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["month_name"] = df["date"].dt.month_name()

In [10]:
df["year_month"] = df["date"].dt.to_period("M")

In [13]:
df[["date", "year", "month", "month_name", "year_month"]].head()

        date  year  month month_name year_month
0 2026-09-17  2026      9  September    2026-09
1 2026-09-17  2026      9  September    2026-09
2 2026-09-15  2026      9  September    2026-09
3 2026-09-14  2026      9  September    2026-09
4 2026-09-11  2026      9  September    2026-09

In [14]:
df["country"] = df["country"].str.strip()

In [15]:
categorical_cols = [
    "company",
    "location",
    "industry",
    "stage",
    "country"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- company ---
company
Amazon        24
Google        19
Microsoft     17
Salesforce    15
Oracle        12
Intel         12
Rivian        12
Meta          12
TikTok        10
Expedia       10
Uber           9
PayPal         8
Shopify        8
Spotify        8
Unity          8
Name: count, dtype: int64

--- location ---
location
SF Bay Area            1141
New York City           455
Seattle                 202
Bengaluru, Non-U.S.     200
Boston                  195
Tel Aviv, Non-U.S.      171
Los Angeles             171
London, Non-U.S.        142
Berlin, Non-U.S.        100
Toronto, Non-U.S.        83
Austin                   77
Sao Paulo, Non-U.S.      69
Chicago                  58
Singapore, Non-U.S.      57
Sydney, Non-U.S.         54
Name: count, dtype: int64

--- industry ---
industry
Finance           549
Retail            364
Healthcare        336
Consumer          318
Other             315
Transportation    277
Food              257
Marketing         223
Crypto            181
Security          169
Real Estate       167
Education         166
Media             163
Data              145
HR                115
Name: count, dtype: int64

--- stage ---
stage
Post-IPO          1115
Unknown            775
Series B           495
Series C           456
Acquired           419
Series D           366
Series A           276
Series E           208
Seed               159
Series F           128
Private Equity      86
Series H            36
Subsidiary          31
Series G            29
Series J            12
Name: count, dtype: int64

--- country ---
country
United States     2897
India              351
Israel             188
Canada             181
United Kingdom     160
Germany            136
Brazil              90
Australia           88
Singapore           59
Sweden              46
Indonesia           41
Nigeria             39
China               31
Netherlands         31
France              23
Name: count, dtype: int64

In [16]:
for col in categorical_cols:
    df[col] = df[col].str.strip()

In [18]:
missing = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    "missing_percentage",
    ascending=False
)

missing

                     missing_count  missing_percentage
percentage_laid_off           1722           37.369792
total_laid_off                1598           34.678819
funds_raised                   549           11.914062
stage                            8            0.173611
source                           3            0.065104
industry                         2            0.043403
country                          2            0.043403
location                         1            0.021701
company                          0            0.000000
date                             0            0.000000
date_added                       0            0.000000
year                             0            0.000000
month                            0            0.000000
month_name                       0            0.000000
year_month                       0            0.000000

In [19]:
df["total_laid_off_missing"] = df["total_laid_off"].isna()

In [20]:
df["total_laid_off_missing"].value_counts()

total_laid_off_missing
False    3010
True     1598
Name: count, dtype: int64

In [21]:
df["percentage_laid_off_missing"] = df["percentage_laid_off"].isna()

In [22]:
df["funds_raised_missing"] = df["funds_raised"].isna()

In [23]:
df["total_laid_off"].describe()

count     3010.000000
mean       309.777741
std       1112.244640
min          3.000000
25%         40.000000
50%         90.000000
75%        200.000000
max      22000.000000
Name: total_laid_off, dtype: float64

In [24]:
df["total_laid_off"].sort_values().head(10)

4087    3.0
338     3.0
4252    4.0
4378    4.0
4600    4.0
3331    5.0
4432    5.0
4057    5.0
1987    5.0
3237    5.0
Name: total_laid_off, dtype: float64

In [25]:
df["total_laid_off"].sort_values(ascending=False).head(10)

551     22000.0
125     21000.0
313     16000.0
869     15000.0
1036    14000.0
388     14000.0
2508    12000.0
264     11000.0
2993    11000.0
2182    10000.0
Name: total_laid_off, dtype: float64

In [26]:
df["percentage_laid_off"].describe()

count    2886.000000
mean        0.296115
std         0.306948
min         0.000000
25%         0.100000
50%         0.170000
75%         0.330000
max         1.000000
Name: percentage_laid_off, dtype: float64

In [27]:
df["percentage_laid_off"].min(), df["percentage_laid_off"].max()

(0.0, 1.0)

In [28]:
df[df["percentage_laid_off"] > 1]

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added, year, month, month_name, year_month, total_laid_off_missing, percentage_laid_off_missing, funds_raised_missing]
Index: []

In [32]:
Q1 = df["total_laid_off"].quantile(0.25)
Q3 = df["total_laid_off"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [33]:
outliers = df[
    (df["total_laid_off"] < lower_bound) |
    (df["total_laid_off"] > upper_bound)
]

outliers.shape

(353, 18)

In [35]:
df[df["total_laid_off"] < 0]

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added, year, month, month_name, year_month, total_laid_off_missing, percentage_laid_off_missing, funds_raised_missing]
Index: []

In [36]:
df[df["funds_raised"] < 0]

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added, year, month, month_name, year_month, total_laid_off_missing, percentage_laid_off_missing, funds_raised_missing]
Index: []

In [37]:
df[
    (df["percentage_laid_off"] < 0) |
    (df["percentage_laid_off"] > 1)
]

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added, year, month, month_name, year_month, total_laid_off_missing, percentage_laid_off_missing, funds_raised_missing]
Index: []

In [38]:
df["date"].min(), df["date"].max()

(Timestamp('2020-03-11 00:00:00'), Timestamp('2026-09-17 00:00:00'))

In [39]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Rows: 4608
Columns: 18

Missing values:
company                           0
location                          1
total_laid_off                 1598
date                              0
percentage_laid_off            1722
industry                          2
source                            3
stage                             8
funds_raised                    549
country                           2
date_added                        0
year                              0
month                             0
month_name                        0
year_month                        0
total_laid_off_missing            0
percentage_laid_off_missing       0
funds_raised_missing              0
dtype: int64

Duplicate rows:
0

Data types:
company                                object
location                               object
total_laid_off                        float64
date                           datetime64[ns]
percentage_laid_off                   float64
industry                               object
source                                 object
stage                                  object
funds_raised                          float64
country                                object
date_added                     datetime64[ns]
year                                    int32
month                                   int32
month_name                             object
year_month                          period[M]
total_laid_off_missing                   bool
percentage_laid_off_missing              bool
funds_raised_missing                     bool
dtype: object

In [40]:
df.head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added,year,month,month_name,year_month,total_laid_off_missing,percentage_laid_off_missing,funds_raised_missing
0,Trustly,"Stockholm, Non-U.S.",200.0,2026-09-17,NaN,Finance,https://tech.eu/2026/09/17/swedish-fintech-tru...,Acquired,28.0,Sweden,2026-09-17,2026,9,September,2026-09,False,True,False
1,Bluevine,"Bengaluru, Non-U.S.",80.0,2026-09-17,NaN,Finance,https://www.ndtv.com/offbeat/team-of-80-indian...,Unknown,769.0,India,2026-09-17,2026,9,September,2026-09,False,True,False
2,Pulley,SF Bay Area,NaN,2026-09-15,1.0,Finance,https://www.businessinsider.com/pulley-shuts-d...,Series B,50.0,United States,2026-09-16,2026,9,September,2026-09,True,False,False
3,Oracle,SF Bay Area,NaN,2026-09-14,NaN,Other,https://www.businessinsider.com/oracle-begins-...,Post-IPO,NaN,United States,2026-09-16,2026,9,September,2026-09,True,True,True
4,Bitcoin Suisse,"Zurich, Non-U.S.",60.0,2026-09-11,0.5,Crypto,https://www.reuters.com/business/world-at-work...,Series A,NaN,Switzerland,2026-09-14,2026,9,September,2026-09,False,False,True